### ISSUE TITLE
Creating several clients in one application causes "Duplicate add MessageReader" exception

### ISSUE THREAD

**Issue by shaunthesheep644** [willardf/Hazel-Networking#1]
After last update i begin to receive this when create two clients in one application

Unhandled Exception: System.Exception: Duplicate add MessageReader
   at Hazel.ObjectPool`1.PutObject(T item) in /Users/mtiganov/dev/MS.Shaman.Server/Shaman.Server/Network/Hazel/ObjectPool.cs:line 74
   at Hazel.MessageReader.Recycle() in /Users/mtiganov/dev/MS.Shaman.Server/Shaman.Server/Network/Hazel/MessageReader.cs:line 128
   at Hazel.Udp.UdpConnectionListener.StartListeningForData() in /Users/mtiganov/dev/MS.Shaman.Server/Shaman.Server/Network/Hazel/Udp/UdpConnectionListener.cs:line 131
   at Hazel.Udp.UdpConnectionListener.ReadCallback(IAsyncResult result) in /Users/mtiganov/dev/MS.Shaman.Server/Shaman.Server/Network/Hazel/Udp/UdpConnectionListener.cs:line 190
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback()
   at System.Net.ContextAwareResult.<>c.<Complete>b__15_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionCallback(Int32 numBytes, SocketError errorCode)
   at System.Net.Sockets.OverlappedAsyncResult.CompletionCallback(Int32 numBytes, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError errorCode)
   at System.Net.Sockets.SocketAsyncContext.BufferMemoryReceiveOperation.InvokeCallback(Boolean allowPooling)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.<>c.<.cctor>b__18_0(Object op)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by willardf** [comment]
Which commit are you on? I introduced some bad code in dc3a00f (July 25) that produced that kind of error, but fixed it in the next commit. Is it possible you're between them?

Otherwise, it'd be nice to hear what kind of circumstance produces this error since I'm not seeing it myself.

**Comment by shaunthesheep644** [comment]
I made pull while i was on commit https://github.com/willardf/Hazel-Networking/commit/38c8747a67ab01b4baf01bb90ca1d7fe2ac985ec (21 june). I'll try to describe circumstances later

**Comment by shaunthesheep644** [comment]
i found problem and i tried to create pull request - but i do not have permissions. 
Just update line 115 in UdpConnectionListener:
this.Logger("Operation completed synchronously");
Logger throws nullref and after that second Catch block also throws exception mentioned in topic start. "message.Recycle();" is not very safe in catch block

**Comment by shaunthesheep644** [comment]
Created pull request
